def draw_park(trees=3):
    print("      /" + "\\")
    print("     ----")
    print("    /    " + "\\")
    print("   --------")
    print("  /        " + "\\")
    print(" ------------")
    print("/            " + "\\")
    print("---------------")
    print("      |_|")
    print("      /" + "\\")
    print("     ----")
    print("    /    " + "\\")
    print("   --------")
    print("  /        " + "\\")
    print(" ------------")
    print("/            " + "\\")
    print("---------------")
    print("      |_|")
    print("      /" + "\\")
    print("     ----")
    print("    /    " + "\\")
    print("   --------")
    print("  /        " + "\\")
    print(" ------------")
    print("/            " + "\\")
    print("---------------")
    print("      |_|")	    
    print("                          |          ")
    print("      squirrel            |          ")
    print("                          |          ")
    print("                          |          ")
    print("   water fountain         |          ")
    print("                          |          ")
    print("                          |          ")
    print("   Benches                |          ")
    print(" --------------  ")
    print("(  . ~This    )")
    print("(     is  ~   )")
    print("(  ~   GREEN  .  )")
    print("(  .  POND ~  )")
    print(" --------------  ")	
    return	

